AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  ContainerizeSatimagePreview:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageConfig:
        Command: ["src/lambda_function.lambda_handler"]
      #CodeUri: ./
      #Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 60
      Policies: AWSLambdaExecute
      Events:
        ContainerizeSatimagePreviewEvent:
          Type: S3
          Properties:
            Bucket: !Ref SrcBucket
            Events: s3:ObjectCreated:*
    Metadata:
      DockerContext: ./
      Dockerfile: Dockerfile
  SrcBucket:
    Type: AWS::S3::Bucket
